name: Build and Upload Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn run build:voxelview
        
      - name: Verify files
        run: ls ./platform/app/
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: voxelview-build
          path: ./platform/app/compressed/voxelview-build.tar.gz
          retention-days: 30  # Ajuste o número de dias conforme necessário
